;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/6/13 12:44:01

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1040	1040	; API 帮助 help-doc.html
#define IDH_1027	1027	; 已过时的列表 deprecated-list.html
#define IDH_1064	1064	; 程序包的使用 package-use.html
#define IDH_1062	1062	; 程序包摘要 package-summary.html
#define IDH_1000	1000	; 框架所有类 allclasses-frame.html
#define IDH_1001	1001	; 无框架所有类 allclasses-noframe.html
#define IDH_1057	1057	; 概览 index.html
#define IDH_1060	1060	; 类分层结构 overview-tree.html
#define IDH_1063	1063	; 类分层树结构 package-tree.html
#define IDH_1004	1004	; 常量字段值 constant-values.html
#define IDH_1065	1065	; 序列化表格 serialized-form.html
#define IDH_1059	1059	; 无目录概览 overview-summary.html
#define IDH_1058	1058	; 概览列表 overview-frame.html
#define IDH_1003	1003	; 测试类 CommandT.html
#define IDH_1061	1061	; 包框架 package-frame.html
#define IDH_1002	1002	; 类 CommandT的使用 class-use\CommandT.html
#define IDH_1005	1005	; ArticleServlet controller\ArticleServlet.html
#define IDH_1009	1009	; controller controller\package-frame.html
#define IDH_1010	1010	; controller controller\package-summary.html
#define IDH_1011	1011	; controller类分层结构 controller\package-tree.html
#define IDH_1013	1013	; TypeServlet controller\TypeServlet.html
#define IDH_1014	1014	; UserServlet controller\UserServlet.html
#define IDH_1012	1012	; 程序包controller的使用 controller\package-use.html
#define IDH_1006	1006	; 类controller.ArticleServlet的使用 controller\class-use\ArticleServlet.html
#define IDH_1007	1007	; 类controller.TypeServlet的使用 controller\class-use\TypeServlet.html
#define IDH_1008	1008	; 类controller.UserServlet的使用 controller\class-use\UserServlet.html
#define IDH_1015	1015	; ArticlesOperation dao\ArticlesOperation.html
#define IDH_1021	1021	; dao dao\package-frame.html
#define IDH_1022	1022	; dao dao\package-summary.html
#define IDH_1023	1023	; dao 类分层结构 dao\package-tree.html
#define IDH_1020	1020	; MailOperation dao\MailOperation.html
#define IDH_1025	1025	; UsersOperation dao\UsersOperation.html
#define IDH_1026	1026	; Weather dao\Weather.html
#define IDH_1024	1024	; 程序包dao的使用 dao\package-use.html
#define IDH_1016	1016	; 类dao.ArticlesOperation的使用 dao\class-use\ArticlesOperation.html
#define IDH_1017	1017	; 类dao.MailOperation的使用 dao\class-use\MailOperation.html
#define IDH_1018	1018	; 类dao.UsersOperation的使用 dao\class-use\UsersOperation.html
#define IDH_1019	1019	; 类dao.Weather的使用 dao\class-use\Weather.html
#define IDH_1028	1028	; Articles entity\Articles.html
#define IDH_1033	1033	; Comments entity\Comments.html
#define IDH_1034	1034	; entity entity\package-frame.html
#define IDH_1035	1035	; entity entity\package-summary.html
#define IDH_1036	1036	; entity 类分层结构 entity\package-tree.html
#define IDH_1038	1038	; Types entity\Types.html
#define IDH_1039	1039	; Users entity\Users.html
#define IDH_1037	1037	; 程序包 entity的使用 entity\package-use.html
#define IDH_1029	1029	; 类entity.Articles的使用 entity\class-use\Articles.html
#define IDH_1030	1030	; 类entity.Comments的使用 entity\class-use\Comments.html
#define IDH_1031	1031	; 类entity.Types的使用 entity\class-use\Types.html
#define IDH_1032	1032	; 类entity.Users的使用 entity\class-use\Users.html
#define IDH_1041	1041	; A - 索引 index-files\index-1.html
#define IDH_1049	1049	; C - 索引 index-files\index-2.html
#define IDH_1050	1050	; D - 索引 index-files\index-3.html
#define IDH_1051	1051	; E - 索引 index-files\index-4.html
#define IDH_1052	1052	; F - 索引 index-files\index-5.html
#define IDH_1053	1053	; G - 索引 index-files\index-6.html
#define IDH_1054	1054	; I - 索引 index-files\index-7.html
#define IDH_1055	1055	; L - 索引 index-files\index-8.html
#define IDH_1056	1056	; M - 索引 index-files\index-9.html
#define IDH_1042	1042	; P - 索引 index-files\index-10.html
#define IDH_1043	1043	; Q - 索引 index-files\index-11.html
#define IDH_1044	1044	; R - 索引 index-files\index-12.html
#define IDH_1045	1045	; S - 索引 index-files\index-13.html
#define IDH_1046	1046	; T - 索引 index-files\index-14.html
#define IDH_1047	1047	; U - 索引 index-files\index-15.html
#define IDH_1048	1048	; W - 索引 index-files\index-16.html
#define IDH_1066	1066	; Abstract utils\Abstract.html
#define IDH_1067	1067	; C3p0Con utils\C3p0Con.html
#define IDH_1075	1075	; Encrypt utils\Encrypt.html
#define IDH_1076	1076	; Filter1 utils\Filter1.html
#define IDH_1077	1077	; Filter2 utils\Filter2.html
#define IDH_1082	1082	; Page utils\Page.html
#define IDH_1078	1078	; utils utils\package-frame.html
#define IDH_1079	1079	; utils utils\package-summary.html
#define IDH_1080	1080	; utils 类分层结构 utils\package-tree.html
#define IDH_1083	1083	; UUIDUtils utils\UUIDUtils.html
#define IDH_1081	1081	; 程序包 utils的使用 utils\package-use.html
#define IDH_1068	1068	; 类 utils.Abstract的使用 utils\class-use\Abstract.html
#define IDH_1069	1069	; 类 utils.C3p0Con的使用 utils\class-use\C3p0Con.html
#define IDH_1070	1070	; 类 utils.Encrypt的使用 utils\class-use\Encrypt.html
#define IDH_1071	1071	; 类 utils.Filter1的使用 utils\class-use\Filter1.html
#define IDH_1072	1072	; 类 utils.Filter2的使用 utils\class-use\Filter2.html
#define IDH_1073	1073	; 类 utils.Page的使用 utils\class-use\Page.html
#define IDH_1074	1074	; 类 utils.UUIDUtils的使用 utils\class-use\UUIDUtils.html
